# Copyright 2023 Canonical
# See LICENSE file for licensing details.

[tox]
isolated_build = True
skip_missing_interpreters = True
envlist = unit, lint

[testenv:unit]
description = run unittests
deps =
    pytest
commands =
    pytest -v --tb native {toxinidir}/tests --log-cli-level=INFO -s {posargs}


[testenv:lint]
skip_install = True
description = run linters (check only)
allowlist_externals =
    uv
commands =
    uv run --active --with black black --check ./


[testenv:fmt]
skip_install=True
description = run formatters
allowlist_externals =
    uv
commands =
    uv run --active --with black black ./
