name: Integration Tests

on:
  workflow_call:

permissions:
  actions: read
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.collect.outputs.tests }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
      - name: Collect integration tests
        id: collect
        run: |
          set -xueo pipefail
          tests=$(uv run --group integration pytest --collect-only -q --no-header tests/integration | grep '::' | jq -R -s -c '[split("\n")[] | select(. != "")]')
          echo "tests=$tests" >> "$GITHUB_OUTPUT"

  pack-simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install concierge
        run: sudo snap install --classic concierge
      - name: Prepare pack environment
        run: sudo concierge prepare -c .github/concierge/pack.yaml
      - name: Pack charm
        run: charmcraft pack --platform amd64
        working-directory: tests/integration/charms/simple
      - name: Upload charm artifact
        uses: actions/upload-artifact@v4
        with:
          name: charm
          path: "tests/integration/charms/simple/*.charm"
          if-no-files-found: error

  test:
    needs: [init]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ${{ fromJson(needs.init.outputs.tests) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install concierge
        run: sudo snap install --classic concierge
      - name: Prepare test environment
        run: sudo concierge prepare -c .github/concierge/test.yaml
      - uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
      - run: uv tool install tox --with tox-uv
      - name: Wait for pack job
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/wait-for-job.py pack-simple
      - name: Download charm
        uses: actions/download-artifact@v4
        with:
          name: charm
      - env:
          CHARM_PATH: ${{ github.workspace }}/simple_amd64.charm
        run: tox -e integration -- ${{ matrix.test }}
