name: Integration Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.tests.outputs.result }}
      charms: ${{ steps.charms.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
      - name: Collect integration tests
        id: tests
        run: |
          set -xueo pipefail
          result=$(uv run --group integration pytest --collect-only -q --no-header tests/integration | grep '::' | jq -Rnc '[inputs]')
          echo "result=$result" >> "$GITHUB_OUTPUT"
      - name: Collect charm directories
        id: charms
        run: |
          set -xueo pipefail
          result=$(find tests/integration/charms -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | jq -Rnc '[inputs]')
          echo "result=$result" >> "$GITHUB_OUTPUT"

  pack:
    needs: [init]
    strategy:
      fail-fast: true
      matrix:
        charm: ${{ fromJson(needs.init.outputs.charms) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: sudo snap install --classic concierge
      - run: sudo concierge prepare -c .github/concierge/pack.yaml
      - run: charmcraft pack --platform amd64
        working-directory: tests/integration/charms/${{ matrix.charm }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.charm }}-charm
          path: "tests/integration/charms/${{ matrix.charm }}/*.charm"
          if-no-files-found: error

  needs-pack:
    needs: [pack]
    if: ${{ !cancelled() }}
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Cancel workflow if pack failed
        if: needs.pack.result == 'failure'
        # https://cli.github.com/manual/gh_run_cancel
        run: gh run cancel --repo ${{ github.repository }} ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    permissions:
      actions: read
      contents: read
    needs: [init]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.init.outputs.tests) }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: sudo snap install --classic concierge
      - run: sudo concierge prepare -c .github/concierge/test.yaml
      - uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098  # v7.3.1
      - run: uv tool install tox --with tox-uv
      - run: python .github/wait-for-job.py needs-pack
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-charm"
          merge-multiple: true
      - name: Set *CHARM_PATH env vars
        run: |
          for charm in *.charm; do
            name=${charm%%_*}  # strip from first underscore to end: simple_amd64.charm -> simple
            name=${name//-/_}  # replace hyphens with underscores: my-charm -> my_charm
            # uppercase and append suffix: simple -> SIMPLE_CHARM_PATH
            echo "${name^^}_CHARM_PATH=${{ github.workspace }}/${charm}" >> "$GITHUB_ENV"
          done
      - run: tox -e integration -- ${{ matrix.test }}
