name: Tests

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Lint
        run: |
          sudo snap install astral-uv --classic
          uv run --active --with black black --check ./

  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Unit tests
        run: |
          sudo snap install astral-uv --classic
          uv run --with pytest pytest -v --tb native ./tests --log-cli-level=DEBUG

  backup-operators-integration-tests:
    runs-on: ubuntu-latest
    steps:
      # From operator-workflows
      # Avoid autorefresh during testing
      - name: Disable snap autorefresh
        run: sudo snap refresh --hold=2h
      - name: Wait for last autorefresh
        run: sudo snap watch --last=auto-refresh?
        timeout-minutes: 10
      # Free up disk space
      - name: Remove Android SDK
        run: sudo rm -rf /usr/local/lib/android
      # Set up Juju, Charmcraft, LXD, tox
      - name: Setup operator environment (LXD + Juju)
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: 3/stable
          channel: latest/stable
          bootstrap-constraints: "cores=2 mem=4G root-disk=10G"

      - name: Checkout charm repo to run integration tests from
        uses: actions/checkout@v4
        with:
          repository: canonical/backup-operators
          path: charm-repo

      # Inject current pytest-jubilant branch as test dependency
      - name: Checkout pytest-jubilant to inject
        uses: actions/checkout@v4
        with:
          path: pytest-jubilant-repo
      - name: Swap pytest-jubilant dependency for checkeded out version
        working-directory: charm-repo
        run: |
          sed -i "s%    pytest-jubilant%    file://${GITHUB_WORKSPACE}/pytest-jubilant-repo%" tox.ini

      - name: Run integration tests
        working-directory: charm-repo
        run: tox -e integration -- --keep-models --base=ubuntu@24.04
