name: TIOBE

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * 0'

permissions: {}

jobs:
  TICS:
    runs-on: [self-hosted, reactive, amd64, tiobe, noble]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990  # v8.3.2

        # We could store the coverage report from the regular run, but this is cheap to do
        # and keeps this isolated.
      - name: Run unit tests and generate coverage report
        run: |
          uv run --only-group tox tox -e unit
          mkdir .report
          uv run --only-group unit coverage xml -o .report/coverage.xml

        # Note that these are dependencies for the tools that the TIOBE action will run,
        # which is done in the global environment, rather than a venv, as we do with the
        # unit tests. Versions for flake8 and pylint are pinned via the `tiobe`
        # dependency group in pyproject.toml.
      - name: Install dependencies
        run: |
          uv export --no-emit-project --frozen --no-hashes --group tiobe > requirements.txt
          pip install -r requirements.txt --break-system-packages

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@74bf696843d3f0980ae6d7a810abe40f82dfcd17  # v3.11.0
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: pytest-jubilant
          installTics: true
